### ISSUE TITLE
What is the quick way of using layout.html in ErrorPageHandler?

### ISSUE THREAD

**Issue by kevinresol** [ufront/ufront-mvc#17]
I understand that we should avoid using template engines in this step but it is essential to have the error page consistent with other pages of the site.

**Comment by jasononeil** [comment]
I guess the issue is more with file-system or network access than template engines.  For example, there is a good chance that a file might load on your local laptop, but fail to load on a server due to unix permissions being wrong.  This is frustrating to debug.  The chances of your template not passing are much smaller.

With that in mind, two possible solutions, both of which involve the [compiletime](https://github.com/jasononeil/compiletime/) library:

 - Use `CompileTime.interpolateFile('error-layout.html');`  This basically uses a macro to insert the whole content of that file in as a String, but uses Haxe string interpolation.  So you can use `<h1>$error</h1><p>${error.code}</p>` or similar.

- Use `new haxe.Template( CompileTime.readFile('website-layout.html') )` to get the template of your main website layout, and parse it.  This inserts the string directly, so no file system access is needed. If there is an error in your layout, at least it will be the same error on your development environment and on the server, so it should be much easier to debug. 

Does that answer the question for you?

**Comment by jasononeil** [comment]
Hopefully the above solutions are enough :)
